### ISSUE TITLE
Invalid criteria on `Query`

### ISSUE THREAD

**Issue by CGMossa** [jakobhellermann/bevycheck#4]
Clippy wants me to annotate all anonymous lifetimes, as they are deprecated. I'm not sure where this is written.
But it means that I have to write `Commands<'_>`, `Query<'_,` and so on. 

Thus, I get an error on a very legitimately correct system:
```rust
error: invalid system parameter

  = note: the query should have generic type parameters      


   --> src\dispersal.rs:362:16
    |
362 |         query: Query<'_, (&VitalStatus, &Sex, &AgeGroup)>,
    |                ^^^^^

```

I hope that this can be fixed. I think this crate is a must have to make working with `bevy` frictionless. 
I'd gladly test or help write the solution for this, if I get some steps on to do this.

**Comment by jakobhellermann** [comment]
The problem was that bevycheck wanted to check the first generic parameter, not the first generic *type* parameter. This is now fixed in https://github.com/jakobhellermann/bevycheck/commit/1caf3db0472d612c85855bb8f3070277d29435a8.
Thanks for reporting the issue!
